
from odoo import fields, models

class DflexPorton(models.Model):
    _name = 'dflex.porton'
    _description = 'Portón (DFLEX)'

    name = fields.Char(string='Nombre / NV', required=True, index=True)
    import_id = fields.Many2one('dflex.porton.import', string='Lote de importación', ondelete='set null')
    source_row = fields.Integer(string='Fila origen')
    specs_json = fields.Json(string='Especificaciones (JSON)')

    x_col_nota_de_venta = fields.Char(string="Nota de Venta")
    x_col_cliente_3000 = fields.Char(string="CLIENTE +3000")
    x_col_direccion_cliente = fields.Char(string="DIRECCION CLIENTE")
    x_col_distribuidor = fields.Char(string="DISTRIBUIDOR")
    x_col_fecha_de_pedido = fields.Char(string="FECHA DE PEDIDO")
    x_col_fecha_de_entrega = fields.Char(string="FECHA DE ENTREGA")
    x_col_fecha_entrega_estimada = fields.Char(string="FECHA ENTREGA ESTIMADA")
    x_col_dias_restantes = fields.Char(string="DIAS RESTANTES")
    x_col_dias_transcurrido = fields.Char(string="DIAS TRANSCURRIDO")
    x_col_estado = fields.Char(string="ESTADO")
    x_revestimiento_fabricante = fields.Char(string="Rev. FABRICANTE")
    x_revestimiento_tipo = fields.Char(string="Rev. TIPO")
    x_revestimiento_lucera = fields.Char(string="Rev. LUCERA")
    x_revestimiento_color_de_simil_aluminio = fields.Char(string="COLOR DE SIMIL ALUMINIO")
    x_revestimiento_liston = fields.Char(string="Rev. LISTON")
    x_revestimiento_partida = fields.Char(string="Rev. PARTIDA")
    x_revestimiento_inicio_produccion = fields.Char(string="Rev. Inicio Produccion")
    x_parantes_cantidad = fields.Char(string="Par. CANTIDAD")
    x_parantes_distribucion = fields.Char(string="Par. DISTRIBUCION")
    x_parantes_color_de_sistema = fields.Char(string="Par. COLOR DE SISTEMA")
    x_puerta_condicion = fields.Char(string="Pue. CONDICION")
    x_puerta_posicion = fields.Char(string="Pue. POSICION")
    x_puerta_descripcion = fields.Char(string="Pue. DESCRIPCION")
    x_puerta_v = fields.Char(string="Pue. v")
    x_motor_condicion = fields.Char(string="Mot. CONDICION.")
    x_motor_doble = fields.Char(string="Mot. DOBLE")
    x_motor_columna4 = fields.Char(string="Mot. Columna4")
    x_pasador_condicion = fields.Char(string="Pas. CONDICION..")
    x_puerta_armado_puerta = fields.Char(string="Pue. ARMADO PUERTA")
    x_puerta_columna7 = fields.Char(string="Pue. Columna7")
    x_instalacion_instalador = fields.Char(string="Ins. INSTALADOR")
    x_instalacion_empotra_duras = fields.Char(string="Ins. EMPOTRA DURAS")
    x_instalacion_posicion = fields.Char(string="Ins. POSICION.")
    x_instalacion_columna9 = fields.Char(string="Ins. Columna9")
    x_parantes_n_pieza = fields.Char(string="Par. N° PIEZA")
    x_parantes_descripcion = fields.Char(string="Par. DESCRIPCION")
    x_parantes_columna10 = fields.Char(string="Par. Columna10")
    x_piernas_tipo = fields.Char(string="Pie. TIPO.")
    x_piernas_altura = fields.Char(string="Pie. ALTURA")
    x_piernas_espesor_revest = fields.Char(string="Pie. ESPESOR REVEST")
    x_dintel_tipo = fields.Char(string="Din. TIPO…")
    x_dintel_ancho = fields.Char(string="Din. ANCHO")
    x_dintel_columna13 = fields.Char(string="Din. Columna13")
    x_datos_brazos = fields.Char(string="Dat. BRAZOS")
    x_datos_hueco_chico = fields.Char(string="Dat. HUECO CHICO")
    x_datos_hueco_grande = fields.Char(string="Dat. HUECO GRANDE")
    x_datos_columna14 = fields.Char(string="Dat. Columna14")
    x_rebaje_si_no = fields.Char(string="Reb. SI/NO")
    x_rebaje_descuento = fields.Char(string="Reb. DESCUENTO")
    x_rebaje_altura = fields.Char(string="Reb. ALTURA.")
    x_rebaje_columna16 = fields.Char(string="Reb. Columna16")
    x_rebaje_lateral_e_inferior_si_no2 = fields.Char(string="Reb. SI/NO2")
    x_rebaje_lateral_e_inferior_descuento_2 = fields.Char(string="Reb. DESCUENTO 2")
    x_rebaje_lateral_e_inferior_observaciones = fields.Char(string="Reb. Observaciones")
    x_motores_que_faltan_col = fields.Char(string="Motores que faltan")
    x_motores_que_faltan_col_2 = fields.Char(string="Motores que faltan")
    x_motores_que_faltan_col_3 = fields.Char(string="Motores que faltan")
    x_motores_que_faltan_largo_del_braso = fields.Char(string="Mot. LARGO DEL BRASO")
    x_motores_que_faltan_ancho_tot_de_hoja = fields.Char(string="Mot. ANCHO TOT DE HOJA")
    x_motores_que_faltan_puerta = fields.Char(string="Mot. PUERTA")
    x_motores_que_faltan_cant_de_lama = fields.Char(string="Mot. Cant de lama")
    x_motores_que_faltan_panos_la_puerta = fields.Char(string="Mot. PAÑOS + LA PUERTA")
    x_motores_que_faltan_largo_de_las_lamas = fields.Char(string="Mot. LARGO DE LAS LAMAS")
    x_motores_que_faltan_cantidad_de_chapas = fields.Char(string="Mot. CANTIDAD DE CHAPAS")
    x_motores_que_faltan_largo_de_parantes = fields.Char(string="Mot. LARGO DE PARANTES")
    x_motores_que_faltan_cantidad_de_parantes = fields.Char(string="Mot. CANTIDAD DE PARANTES")
    x_motores_que_faltan_largo_de_tapajuntas = fields.Char(string="Mot. LARGO DE TAPAJUNTAS")
    x_motores_que_faltan_cantidad_de_tapajuntas = fields.Char(string="Mot. CANTIDAD DE TAPAJUNTAS")
    x_motores_que_faltan_largo_de_bordes_i_s = fields.Char(string="Mot. LARGO DE BORDES I/S")
    x_motores_que_faltan_cant_de_bordes_i_s = fields.Char(string="Mot. CANT DE BORDES I/S")
    x_movim_col = fields.Char(string="MOVIM")
    x_pernos_col = fields.Char(string="PERNOS")
    x_pernos_distribuidores = fields.Char(string="Per. DISTRIBUIDORES")
    x_pernos_col_2 = fields.Char(string="PERNOS")
    x_pernos_col_3 = fields.Char(string="PERNOS")
    x_pernos_si_fuera_aluminio = fields.Char(string="Per. SI FUERA ALUMINIO")
    x_pernos_col_4 = fields.Char(string="PERNOS")
    x_pernos_col_5 = fields.Char(string="PERNOS")
    x_pernos_col_6 = fields.Char(string="PERNOS")
    x_pernos_col_7 = fields.Char(string="PERNOS")
    x_pernos_col_8 = fields.Char(string="PERNOS")
    x_pernos_col_9 = fields.Char(string="PERNOS")
    x_pernos_col_10 = fields.Char(string="PERNOS")
    x_pernos_col_11 = fields.Char(string="PERNOS")
    x_pernos_estado = fields.Char(string="Per. ESTADO")
    x_pernos_color = fields.Char(string="Per. COLOR")
    x_pernos_ancho = fields.Char(string="Per. ANCHO")
    x_pernos_alto = fields.Char(string="Per. ALTO")
    x_pernos_lucera = fields.Char(string="Per. LUCERA")
    x_pernos_puerta = fields.Char(string="Per. PUERTA")
    x_pernos_col_12 = fields.Char(string="PERNOS")
    x_pernos_chapas = fields.Char(string="Per. CHAPAS")
    x_pernos_parantes_comunes = fields.Char(string="Per. PARANTES COMUNES")
    x_parantes_anchos_cantidad = fields.Char(string="Par. CANTIDAD")
    x_parantes_anchos_medida = fields.Char(string="Par. MEDIDA")
    x_parantes_anchos_col = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_2 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_3 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_4 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_5 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_6 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_7 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_8 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_9 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_10 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_11 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_12 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_13 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_14 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_15 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_16 = fields.Char(string="PARANTES ANCHOS")
    x_parantes_anchos_col_17 = fields.Char(string="PARANTES ANCHOS")
    x_chapa_ancha = fields.Char(string="Cha. ANCHA")
    x_chapa_comun = fields.Char(string="Cha. COMUN")
    x_chapa_angosta = fields.Char(string="Cha. ANGOSTA")
    x_chapa_col = fields.Char(string="CHAPAS")
    x_chapa_col_2 = fields.Char(string="CHAPAS")
    x_chapa_plazo_entrega = fields.Char(string="Cha. Plazo Entrega")
