{
    'name': 'HR Employee Ledger',
    'version': '18.0.2.0.0',
    'summary': 'Cuenta corriente de empleados (A/B), cierre mensual editable y recibo PDF.',
    'author': 'ChatGPT Assistant',
    'website': 'https://example.com',
    'license': 'LGPL-3',
    'category': 'Human Resources',
    'depends': ['hr', 'account', 'analytic'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/hr_employee_ledger_views.xml',
        'views/batch_wizard_views.xml',
        'views/batch_views.xml',
        'views/res_company_views.xml',
        'reports/employee_payment_receipt.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}